name: Hello on Push

on:
    push:
        branches: ["main"] # this works, but not the one below
#            - main    Note: This way of branch config does not work
#    pull_request:
#        branches: ["main"] # this works, but not the one below

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello on Push
              run: echo "Hello, World! Push event triggered."

            - name: Print Event Details for hello on push
              run: |
              #  echo "${{ toJson(github) }}"
                echo "All Configs: ${{ github }}"
                echo "Repository: ${{ github.repository }}"
                echo "Branch: ${{ github.ref }}"
                echo "Commit: ${{ github.sha }}"
